float:
  any:
    - base_args: [ '@metric' ]
      constructor: MatrixOne
      disabled: false
      docker_tag: ann-benchmarks-matrixone
      module: ann_benchmarks.algorithms.matrixone
      name: matrixone
      run_groups:
        matrixone:
          args: [ [ 100, 200, 400, 1000, 2000, 4000 ] ]
          query_args: [ [ 1, 2, 4, 10, 20, 40, 100 ] ]
